module.exports = {
  book: [
    {
      type: 'category',
      label: '更新與勘誤',
      items: [
        'book/errata/book',
        'book/errata/react-version',
        'book/errata/create-react-app',
        'book/errata/emotion',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 0 - 前言',
      items: ['book/ch0/0-1', 'book/ch0/0-2', 'book/ch0/0-3'],
    },
    {
      type: 'category',
      label: 'Chapter 1 - React 中一定會用到的 JavaScript 語法',
      items: [
        'book/ch1/1-1',
        'book/ch1/1-2',
        'book/ch1/1-3',
        'book/ch1/1-4',
        'book/ch1/1-5',
        'book/ch1/1-6',
        'book/ch1/1-7',
        'book/ch1/1-8',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2 - React Hooks 起來：useState 與 JSX 的使用',
      items: [
        'book/ch2/2-1',
        'book/ch2/2-2',
        'book/ch2/2-3',
        'book/ch2/2-4',
        'book/ch2/2-5',
        'book/ch2/2-6',
        'book/ch2/2-7',
        'book/ch2/2-8',
        'book/ch2/2-9',
        'book/ch2/2-10',
        'book/ch2/2-11',
        'book/ch2/2-12',
        'book/ch2/2-13',
        'book/ch2/2-14',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3 - React 元件間的資料傳遞：props 的應用',
      items: [
        'book/ch3/3-1',
        'book/ch3/3-2',
        'book/ch3/3-3',
        'book/ch3/3-4',
        'book/ch3/3-5',
        'book/ch3/3-6',
        'book/ch3/3-7',
        'book/ch3/3-8',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4 - 在 JavaScript 中撰寫 CSS 樣式',
      items: [
        'book/ch4/4-1',
        'book/ch4/4-2',
        'book/ch4/4-3',
        'book/ch4/4-4',
        'book/ch4/4-5',
        'book/ch4/4-6',
        'book/ch4/4-7',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5 - 串接 API：useEffect 與 useCallback',
      items: [
        'book/ch5/5-1',
        'book/ch5/5-2',
        'book/ch5/5-3',
        'book/ch5/5-4',
        'book/ch5/5-5',
        'book/ch5/5-6',
        'book/ch5/5-7',
        'book/ch5/5-8',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 6 - 進階資料處理與客製化 React Hooks',
      items: [
        'book/ch6/6-1',
        'book/ch6/6-2',
        'book/ch6/6-3',
        'book/ch6/6-4',
        'book/ch6/6-5',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 7 - 表單處理與頁面間的切換',
      items: [
        'book/ch7/7-1',
        'book/ch7/7-2',
        'book/ch7/7-3',
        'book/ch7/7-4',
        'book/ch7/7-5',
        'book/ch7/7-6',
        'book/ch7/7-7',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 8 - 網站部署與未來學習方向',
      items: ['book/ch8/8-1', 'book/ch8/8-2', 'book/ch8/8-3'],
    },
  ],
  bootcamp: [
    {
      type: 'category',
      label: 'Week1 - React 基礎',
      items: [
        'bootcamp/week1/jsx-basic',
        'bootcamp/week1/use-state',
        'bootcamp/week1/when-to-use-function-in-setstate',
        'bootcamp/week1/event-handler',
        'bootcamp/week1/class-component',
      ],
    },
    {
      type: 'category',
      label: 'Week2 - React 的元件拆分與資料流',
      items: ['bootcamp/week2/todo-mvc'],
    },
    {
      type: 'category',
      label: 'Week3 - useEffect 與 API 串接',
      items: [
        'bootcamp/week3/edit-todo-item',
        'bootcamp/week3/api-integration',
      ],
    },
    {
      type: 'category',
      label: 'Week4 - 使用第三方登入',
      items: [
        'bootcamp/week4/switch-between-pages',
        'bootcamp/week4/create-react-app-setting',
        'bootcamp/week4/facebook-login',
        'bootcamp/week4/custom-hooks',
        'bootcamp/week4/use-context',
      ],
    },
  ],
};
